import React, {Component, PropTypes} from 'react';
import {Header} from 'components';
import {ContentComponents, PageContent} from 'components';
const {P, HR, A} = ContentComponents;

export default class Imprint extends Component {
  static propTypes = {
    state: PropTypes.object
  };

  render() {
    let {menus} = this.props.state;

    return (
      <div>
        <Header title="Imprint" mini menu={menus.main} />

        <PageContent>
          <P>Jan Amann – Frontend Developer</P>
          <P>
            57 Lee house<br />
            Custom House Square<br />
            IFSC Dublin 1<br />
            Ireland
          </P>
          <P>
            E-Mail: <A href="mailto:jan@amann.me">jan@amann.me</A><br />
            Tel: <A href="tel:+353892214412">+353 89 22 14 412</A>
          </P>
          <HR />
          <P small>I do not assume any liability for the contents of external links, although I carefully review their contents. The operators of linked pages are exclusively liable for the contents of their pages.</P>
          <P small>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within an EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser; however, please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</P>
          <P small>You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it: <A href="http://tools.google.com/dlpage/gaoptout">Google Analytics Opt-Out Tool</A>.</P>
        </PageContent>
      </div>
    );
  }
}
