# Revalidate doesn't work for the open source page. The reason is currently
# unknown, but maybe it's due to `App.getInitialProps`. As a workaround we
# use a cron job to redeploy the website.

name: rebuild
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
